{% set version = "0.1.1" %}

package:
  name: datahues
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/datahues/datahues-{{ version }}.tar.gz
  sha256: eddfe625b3337eb0824200cd2ca3c9fed3ddf575294d26d31253ba6466ed537c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.17
    - matplotlib-base >=3.3

test:
  imports:
    - datahues
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aneeshnaik/datahues
  summary: Generate perceptually uniform colour ramps for data visualisation.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aneeshnaik
